### zsh
[[ -s "$HOME/.zsh_local" ]] && source "$HOME/.zsh_local"

export ZSH=$HOME/.oh-my-zsh
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

ZSH_THEME="candy"
CASE_SENSITIVE="true"
DISABLE_AUTO_UPDATE="true"
plugins=(git)

source $ZSH/oh-my-zsh.sh

export LANG=ja_JP.UTF-8
export EDITOR='vim'
export ARCHFLAGS="-arch x86_64"

## メモリ上のヒストリ数。
HISTSIZE=10000000
## 保存するヒストリ数
SAVEHIST=$HISTSIZE
## ^Dでログアウトしないようにする。
setopt ignore_eof
## 履歴検索にワイルドカードを使う
bindkey '^R' history-incremental-pattern-search-backward
bindkey '^S' history-incremental-pattern-search-forward

### rbenv
eval "$(rbenv init -)"

## Docker
eval "$(docker-machine env dev)"

### Go
export GOPATH=$HOME
export PATH=$PATH:$GOPATH/bin

### peco
function peco-src () {
  local selected_dir=$(ghq list --full-path | peco --query "$LBUFFER")
  if [ -n "$selected_dir" ]; then
    BUFFER="cd ${selected_dir}"
    zle accept-line
  fi
  zle clear-screen
}
zle -N peco-src
bindkey '^]' peco-src

