(source gnu)
(source melpa)
(source marmalade)

(depends-on "flycheck")
(depends-on "git-gutter")
(depends-on "multiple-cursors")

(depends-on "js2-mode")
(depends-on "json-mode")
(depends-on "markdown-mode")
(depends-on "ruby-mode")
(depends-on "scala-mode2")
(depends-on "web-mode")
(depends-on "yaml-mode")

(depends-on "ruby-block")
(depends-on "ruby-end")
(depends-on "rubocop")
